// <auto-generated />
namespace pts2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addednew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednew));
        
        string IMigrationMetadata.Id
        {
            get { return "201702020655247_addednew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
