// <auto-generated />
namespace pts2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class update1234 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update1234));
        
        string IMigrationMetadata.Id
        {
            get { return "201702220811005_update1234"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
